--PEGA NOTIFICAÇÕES DE UM DADO $ano E $mes
SELECT ID_NOTIF, LONGITUDE, LATITUDE FROM m_notificacao WHERE YEAR(DATA) = $ano AND MONTH(DATA) = $mes;

--PEGA ANOS DISPONIVEIS NO BANCO
SELECT YEAR(DATA) as ANO from m_notificacao GROUP BY YEAR(DATA);

-- PEGA MESES DE UM ESPECÍFICO $ano
SELECT MONTH(DATA) as MES from m_notificacao WHERE YEAR(DATA) = $ano GROUP BY MONTH(DATA)

-- PEGA OS PROCEDIMENTOS REALIZADOS PARA UMA DETERMINADA NOTIFICAO($id_notif) COM SUAS DEVIDAS DESCRIÇÕES
SELECT n.ID_NOTIF, p.DESCRICAO as PROCEDIMENTO, pr.DESCRICAO as RESULTADO from m_notificacao n
    JOIN m_notificacao_procedimentos np ON np.ID_NOTIF=n.ID_NOTIF AND n.ID_NOTIF=$id_notif
    JOIN m_procedimento p ON p.ID_PROCED=np.ID_PROCED
    JOIN m_procedimento_resultado pr ON pr.ID_PROCED=p.ID_PROCED AND pr.RESULT_N=np.RESULT_N
	
-- PEGA A QUANTIDADE DE CASOS DE DENGUE POR GRUPO E SUAS DESCRIÇÕES
SELECT COUNT(*) as QUANTIDADE, ESCOLARIDADE, RACA, OCUPACAO FROM (
    SELECT g.ID_GRUPO, e.DESCRICAO as ESCOLARIDADE, r.DESCRICAO as RACA, o.DESCRICAO as OCUPACAO FROM m_notificacao n
		LEFT JOIN m_grupo g ON g.ID_GRUPO = n.ID_GRUPO
    	LEFT JOIN m_grupo_escolaridade e ON e.ID_ESCOL=g.ID_ESCOL
    	LEFT JOIN m_grupo_raca r ON r.ID_RACA = g.ID_RACA
    	LEFT JOIN m_grupo_ocupacao o ON o.ID_OCUPA = g.ID_OCUPA
) t GROUP BY t.ID_GRUPO ORDER BY QUANTIDADE DESC

-- PEGA INFORMAÇÕES SOBRE O GRUPO DE UMA NOTIFICAO($id_notif)
select * from(SELECT n.ID_NOTIF, e.DESCRICAO as ESCOLARIDADE, r.DESCRICAO as RACA, o.DESCRICAO as OCUPACAO FROM m_notificacao n
		LEFT JOIN m_grupo g ON g.ID_GRUPO = n.ID_GRUPO
    	LEFT JOIN m_grupo_escolaridade e ON e.ID_ESCOL=g.ID_ESCOL
    	LEFT JOIN m_grupo_raca r ON r.ID_RACA = g.ID_RACA
    	LEFT JOIN m_grupo_ocupacao o ON o.ID_OCUPA = g.ID_OCUPA
) t WHERE t.ID_NOTIF = $id_notif

-- QUANTIDADE PROCEDIMENTOS QUE AFIRMARAM O TIPO DE DENGUE
SELECT t.QUANTIDADE, pr.DESCRICAO as TIPO FROM (SELECT ID_PROCED, RESULT_N, COUNT(*) AS QUANTIDADE FROM m_notificacao_procedimentos WHERE ID_PROCED=4 GROUP BY RESULT_N) t JOIN m_procedimento_resultado pr ON pr.ID_PROCED=t.ID_PROCED AND pr.RESULT_N=t.RESULT_N ORDER BY t.QUANTIDADE DESC

-- QUANTIDADE TOTAL DE CASOS POR ANO NA NOSSA BASE
SELECT YEAR(DATA) AS ANO, COUNT(*) CASOS FROM m_notificacao GROUP BY ANO

-- LISTA DE TODAS AS UNIDADES(TANTO AS QUE EXISTEM NA m_unidades QUANTO AS QUE SÓ TEMOS ID) E A QUANTIDADE DE CASOS ATENDIDOS NELAS
-- OUTERJOIN
SELECT * FROM (
    SELECT t.ID_UNIDADE, t.QUANTIDADE, u.RAZAOSOCIAL FROM (SELECT ID_UNIDADE, COUNT(*) QUANTIDADE FROM m_notificacao GROUP BY ID_UNIDADE) t
    LEFT JOIN m_unidade u ON t.ID_UNIDADE = u.ID_UNIDADE
    UNION 
    SELECT t.ID_UNIDADE, t.QUANTIDADE, u.RAZAOSOCIAL FROM (SELECT ID_UNIDADE, COUNT(*) QUANTIDADE FROM m_notificacao GROUP BY ID_UNIDADE) t
    RIGHT JOIN m_unidade u ON t.ID_UNIDADE = u.ID_UNIDADE
) a ORDER BY QUANTIDADE DESC

-- PORCENTAGEM DE NOTIFICACOES NO MES EM RELAÇÃO AO ANO
SELECT m.MES, m.ANO, CONCAT((m.TOTAL/a.TOTAL)*100, '%') AS PORCENTAGEM FROM (SELECT MONTH(DATA) AS MES, YEAR(DATA) AS ANO, COUNT(*) AS TOTAL FROM m_notificacao GROUP BY MES, ANO ORDER BY ANO ASC) m
JOIN (
	SELECT YEAR(DATA) AS ANO, COUNT(*) AS TOTAL FROM m_notificacao group by ANO
) a ON a.ANO=m.ANO ORDER BY ANO ASC, MES ASC